### ISSUE TITLE
JWT Signature Validation: missing `kid` leads to invalid key error

### ISSUE THREAD

**Issue by moximoti** [caos/oidc#124]
Hi, I'm currently implementing an OIDC RP in Photoprism. So first of all, thank you for this great library!

**Describe the bug**
No matching JWK found, if no `kid` header present in JWT but RemoteKeySet provides a single key with non-empty `kid` value. In this case we get "invalid key" error (pkg/client/rp/jwks.go:91)

**Expected behavior**
Either allow absence of `kid` value in this case and try verification, improve error reporting as the key is valid but could't be found, or automatically add `kid` to both, the remote key set and the corresponding JWT, if it's not provided by storage implementation.

`kid` values are not a MUST, if OP does not provide multiple keys: 
1. https://openid.net/specs/openid-connect-core-1_0.html#Signing
2. https://datatracker.ietf.org/doc/html/rfc7515#section-6

**Comment by livio-a** [comment]
Hi @moximoti 

Thanks for the feedback about the library 😃  and the bug!

I knew the library was no able to validate the signature if no `kid` is in the header but multiple keys are in the key set without `kid` (which is spec compliant).
Apparently it's also not able to validate if `kid` is only missing in the header but not key set.

I should be able to provide you with a fix by tomorrow evening.

**Comment by livio-a** [comment]
Hey @moximoti 

I just created a PR which would change the following:
- FindKey is deprecated in favor of FindMatchingKey which will return an error (ErrKeyNone / ErrKeyMultiple) instead of just the bool
- FindKey will wrap the new FindMatchingKey method to get the changes for finding keys without kid
- FindMatchingKey will iterate through the keys and now check for:
  - `use` and if `alg` header matches the key type
  - then if kid exact match and are not empty, the key is taken
  - or if either kid is empty, the key is appended to the possible keys
- I refactored the VerifySignature of remoteKeySet into multiple methods, in combination with the changes of FindMatching Key, it will now:
  - check for cached keys and if empty, use remote keys directly
  - if a single cached key matches, try to verify the signature
  - on error it will check if kid was empty and then check for new remote keys
  - the remote key check in this case can be disabled by passing `SkipRemoteCheck` into `NewRemoteKeySet` 

This should solve your problem and you could even set the SkipRemoteCheck option if there's only a single key without key rotation.

I will retest the OIDC RP Certification later today and check if there's any other spec violation.
